server:
  port: 8889

spring:
  application:
    name: config-server-git
  cloud:
    config:
      server:
        git:
          uri: "https://github.com/edabykStorage/yenirepo.git"
          default-label: main
          skip-ssl-validation: true
          username: edabykStorage
          password: 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

